//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingInventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.OrdenEntrada = new HashSet<OrdenEntrada>();
            this.OrdenSalida = new HashSet<OrdenSalida>();
            this.OrdenSalida1 = new HashSet<OrdenSalida>();
            this.Producto = new HashSet<Producto>();
        }
        [Key]
        public int id_usuario { get; set; }
        [Required(ErrorMessage = "Debe ingresar nombre")]
        [StringLength(50)]
        [Display(Name ="Nombre")]
        public string nombre { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Required]
        [Display(Name = "Run")]
        public string rut { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Correo")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Contraseña")]
        public string pass { get; set; }
        public int estado { get; set; }
        [Required]
        [Display(Name = "Tipo Usuario")]
        public int id_tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenEntrada> OrdenEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenSalida> OrdenSalida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenSalida> OrdenSalida1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
